name: build-and-test

on: [push]

jobs:

  build-and-test-fixparser:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: whoan/fixparser
